---
title: "Collate, flag and finalize"
author: "Sam Struthers"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

source("scripts/00_setup.R")
```

# Grab each type of data
- Cap rod
- DO
- ISCO

## Cap Rod

```{r}
#render("scripts/01_cap_rod_cleaning.Rmd")
```


## ISCO
### Read in data
```{r}
source("scripts/02_ISCO_binder.R")

# THIS WILL BREAK IF YOU HAVE A FILE OPEN in excel
#Reading in collated 2023 data
raw_isco_xlsx_files <- list.files(
  path = "data/raw/ISCO/", # change to folder path of collated ISCO files
  full.names = TRUE, pattern = ".xlsx")
# read in all isco files
isco_2023 <- map_dfr(raw_isco_xlsx_files, read_isco_file) 

# change to folder path of .dat files
raw_dat_files <- list.files(
  path = "data/raw/ISCO/",   # change to folder path of raw ISCO .dat files
  pattern = ".dat", full.names = TRUE, recursive = TRUE)

#collate and organize all raw data from .dat files
# This is relatively slow (~30 sec per file) so if you are parsing alot of files it may take a few minutes
#isco_2022 <- clean_collate_dat_files(dat_files = raw_dat_files)
# #save collated data
#  write_csv(isco_2022, "data/collated/isco_data_2022.csv")
# write_rds(isco_2022, "data/collated/isco_data_2022.RDS")
# Once it has been run (assuming no new data), you can just load the RDS file for faster opening
isco_2022 <- readRDS(file ="data/collated/isco_data_2022.RDS" )

#combine both user collated and raw .dat files
all_isco <- rbind(isco_2023, isco_2022)%>%
  mutate(turb_rounded = round(turb, digits = 1))
#remove file path vectors
rm(raw_isco_xlsx_files, all_dat_files, dat_folder_path)
```
### Visualize

```{r}
isco_long <- all_isco%>%
  pivot_longer(cols = c(ISCO_temp_c,sc_us, cdom_ave, cdom, turb_ave, turb), names_to = "parameter", values_to = "value")

plot <- ggplot(all_isco, aes(x= DT_round_mst, y= ISCO_temp_c, color= site))+
  geom_line()+
  facet_wrap(~year(DT_round_mst), nrow = 2, scales = "free_x")

ggplotly(plot)
```




## DO
```{r}
#source script with DO binder function
source("scripts/03_miniDOT_binder.R")

#Raw DO folder paths
raw_do_dir <- list.files(path = "data/raw/DO", full.names = TRUE)
# Run all filepaths thru dot puller
all_do <- map_dfr(.x = raw_do_dir, .f = dot_puller)
```
## Check DO

```{r}
DO_plot <- ggplot(all_do, aes(x= DT_round_mst, y= DO_mgL, color= Site))+
  geom_line()+
  geom_smooth()

ggplotly(DO_plot)
```

# Collate all data

```{r}

# List all sites to be processed below
sites <- c("SAWM","FISH", "LBEA", "BLAK" )

create_all_data <- function(site_name){
start_date <- as.POSIXct("2023-01-01 00:00:00", tz = "MST")
end_date <- as.POSIXct("2023-12-31 23:55:00", tz = "MST")

site_data <- tibble(
  Site = site_name,
  DT_round_mst = seq(start_date, end_date, by = "5 min"))

return(site_data)
}

all_data <- map_dfr(sites, create_all_data)%>%
  left_join(all_isco, by = c("Site", "DT_round_mst"))%>%
  left_join(all_do, by = c("Site", "DT_round_mst"))%>%
  filter(rowSums(!is.na(select(., -Site, -DT_round_mst))) > 0)%>%
  mutate(date = as.Date(DT_round_mst))
  

```

### Plot

```{r}



temp_test <- ggplot(data = temp_test, aes(x= DT_round_mst))+
  geom_line( aes( y= temp_diff), color = "blue")

ggplotly(temp_test)
```


# Daily Conversion
 Convert the entire dataframe to daily values
```{r}

all_data_daily <- all_data%>%
  group_by(date, Site)%>%
  summarise(
    mean_do_mgL = mean(DO_mgL, na.rm = TRUE), 
    mean_minidot_temp_c = mean(minidot_temp_c, na.rm = TRUE), 
    mean_ISCO_temp_c = mean(ISCO_temp_c, na.rm = TRUE),
    mean_sc_us  = mean(sc_us, na.rm = TRUE)
  )



```

# Viewing results
```{r}
plot <- ggplot(all_data_daily, aes(x = date)) +
  geom_point(aes(y = mean_minidot_temp_c, color = "Minidot Temp"), size = 1) +
  geom_point(aes(y = mean_ISCO_temp_c, color = "ISCO Temp"), size = 1) +
  labs(x = "Date",
       y = "Mean temp") +
  scale_color_manual(values = c("Minidot Temp" = "red", "ISCO Temp" = "blue")) +
  theme_minimal()+
  facet_wrap(~Site)
ggplotly(plot)
```

```{r}

# Filter data for the same site and on the same day
same_day_data <- all_data_daily %>%
  filter(!is.na(mean_minidot_temp_c) & !is.na(mean_ISCO_temp_c)) %>%
  select(Site, date, mean_minidot_temp_c, mean_ISCO_temp_c)

# Scatter plot with regression line
ggplot(same_day_data, aes(x = mean_minidot_temp_c, y = mean_ISCO_temp_c)) +
  geom_point(aes(color = Site)) +
  #geom_smooth(method = "lm", se = FALSE, color = "blue") +  # Add a linear regression line
  geom_abline(intercept = 0, slope = 1, linetype = "dashed", color = "red") +  # Add a 1:1 line
  labs(title = "Linear Model: Minidot vs. Isco Temperature",
       x = "Minidot Temperature (°C)",
       y = "Isco Temperature (°C)") +
  theme_minimal()

```




